name: together
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  flutter_fortune_wheel: ^1.2.0
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  lottie: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true
  assets:
    - assets/imagens/
    - assets/animations/roleta_lottie.json
  fonts:
    - family: GameFont
      fonts:
        - asset: assets/fonts/RubikGemstones-Regular.ttf

flutter_icons: 
  android: true
  ios: true
  image_path: "assets/icones/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icones/icon.png"
